sudo: false
language: python
env:
  - DJANGO_VERSION="Django>=1.9,<1.10"
  - DJANGO_VERSION="Django>=1.10,<1.11"
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
python:
  - "3.4"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install
  - npm install -g bower
  - npm install less
  - npm install uglify-js -g
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql --no-password travis_ci_test -U postgres -c "create extension postgis"
  - pip install -r test_requirements.txt
  - cd project && cp settings_local_sample.py settings_local.py && cd ..
  - pip install -q "$DJANGO_VERSION"
  - python manage.py collectmedia --noinput
  - ./update.sh no_virtualenv
script:
  - python -Wall $VIRTUAL_ENV/bin/coverage run manage.py test
  - node_modules/karma/bin/karma start karma.conf.js --single-run
after_script:
  - coveralls
addons:
  postgresql: "9.3"
matrix:
   allow_failures:
      - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
