dist: focal
sudo: false
language: python
services:
  - xvfb
env:
  matrix:
    - DJANGO_VERSION="Django>=2.2,<3.0"
    - DJANGO_VERSION="Django>=3.0,<3.1"
    - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
python:
  - "3.9"
before_install:
  - export DISPLAY=:99.0
  - sudo apt-get update && sudo apt-get install curl gnupg && curl https://deb.meteo.guru/velivole-keyring.asc | sudo apt-key add - && sudo echo "deb [arch=amd64] https://deb.meteo.guru/ubuntu focal main" > /etc/apt/sources.list.d/meteo.guru.list && sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends velivole-keyring gdal-bin libgdal-dev unrar
install:
  - pip install pipenv
  - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pipenv install --dev
  - pipenv run pip install flake8_strict
before_script:
  - cp .env.travis .env
  - npm install
  - npm install -g bower less jshint
  - pipenv run pip install -q $DJANGO_VERSION
  - jshint apps/cyklomapa/static/js/*
  - npm install uglify-js@2.8.21 -g  # higher version fails for compress
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql --no-password travis_ci_test -U postgres -c "create extension postgis"
  - python manage.py collectmedia --noinput
  - ./update.sh no_virtualenv
script:
  - django-admin --version
  - pipenv run python -Wall $VIRTUAL_ENV/bin/coverage run manage.py test
  - ./node_modules/.bin/karma start karma.conf.js --single-run
after_script:
  - coveralls
addons:
  postgresql: "12"
  apt:
     packages:
        - postgresql-12-postgis-3.0
        - gdal-bin
matrix:
   allow_failures:
      - env: DJANGO_VERSION="Django>=3.0,<3.1"
      - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
