sudo: false
language: python
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
  - DJANGO_VERSION="Django>=1.10,<1.11"
  - DJANGO_VERSION="Django>=1.11,<1.12"
  - DJANGO_VERSION="Django>=2.0,<2.1"
  - DJANGO_VERSION="Django>=2.1,<2.2"
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
python:
  - "3.5"
  - "3.6"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - npm install
  - npm install -g bower less jshint
  - jshint apps/cyklomapa/static/js/*
  - npm install uglify-js@2.8.21 -g  # higher version fails for compress
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql --no-password travis_ci_test -U postgres -c "create extension postgis"
  - cd project && cp settings_local_sample.py settings_local.py && cd ..
  - pipenv shell
  - pip install -q $DJANGO_VERSION
  - python manage.py collectmedia --noinput
  - ./update.sh no_virtualenv
script:
  - django-admin --version
  - python -Wall $VIRTUAL_ENV/bin/coverage run manage.py test
  - node_modules/karma/bin/karma start karma.conf.js --single-run
after_script:
  - coveralls
addons:
  postgresql: "9.6"
  apt:
     packages:
        - postgresql-9.6-postgis-2.3
matrix:
   allow_failures:
      - env: DJANGO_VERSION="Django>=2.1,<2.2"
      - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
