sudo: false
language: python
env:
  - DJANGO_VERSION="Django>=1.8,<1.9"
  - DJANGO_VERSION="Django>=1.9,<1.10"
python:
  - "2.7"
  - "3.4"
before_script:
  - npm install -g bower
  - npm install less
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql --no-password travis_ci_test -U postgres -c "create extension postgis"
  - pip install -q "$DJANGO_VERSION"
script: 
  - cd project && cp settings_local_sample.py settings_local.py && cd ..
  - ./update.sh no_virtualenv
  - python manage.py test
addons:
  postgresql: "9.3"
matrix:
  allow_failures:
    - env: DJANGO_VERSION="Django>=1.9,<1.10"
