dist: bionic
sudo: false
language: python
services:
  - xvfb
env:
  matrix:
    - DJANGO_VERSION="Django>=2.0,<2.1"
    - DJANGO_VERSION="Django>=2.1,<2.2"
    - DJANGO_VERSION="Django>=2.2,<3.0"
    - DJANGO_VERSION="Django>=3.0,<3.1"
    - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
python:
  - "3.6"
  - "3.7"
before_install:
  - export DISPLAY=:99.0
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pip install flake8_strict
before_script:
  - cp .env.travis .env
  - npm install
  - npm install -g bower less jshint
  - pipenv run pip install -q $DJANGO_VERSION
  - jshint apps/cyklomapa/static/js/*
  - npm install uglify-js@2.8.21 -g  # higher version fails for compress
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql --no-password travis_ci_test -U postgres -c "create extension postgis"
  - python manage.py collectmedia --noinput
  - ./update.sh no_virtualenv
script:
  - django-admin --version
  - pipenv run python -Wall $VIRTUAL_ENV/bin/coverage run manage.py test
  - ./node_modules/.bin/karma start karma.conf.js --single-run
after_script:
  - coveralls
addons:
  postgresql: "10"
  apt:
     packages:
        - postgresql-10-postgis-2.5
        - gdal-bin
matrix:
   allow_failures:
      - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
