sudo: false
language: python
env:
  - DJANGO_VERSION="Django>=1.8,<1.9"
  - DJANGO_VERSION="Django>=1.9,<1.10"
  - DJANGO_VERSION="Django==1.10b1"
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
python:
  - "3.4"
before_script:
  - npm install -g bower
  - npm install less
  - npm install uglify-js -g
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql --no-password travis_ci_test -U postgres -c "create extension postgis"
  - pip install coverage coveralls
  - cd project && cp settings_local_sample.py settings_local.py && cd ..
  - ./update.sh no_virtualenv
  - pip install -q "$DJANGO_VERSION"
script:
  - python -Wall $VIRTUAL_ENV/bin/coverage run manage.py test
after_script:
  - coveralls
addons:
  postgresql: "9.3"
matrix:
   allow_failures:
      - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
