version: '2.1'
services:
 web:
  build: .
  ports:
   - "8033:8000"
  links:
   - postgres
  tty: true
  stdin_open: true
  working_dir: /app-v/
  user: root
  environment:
   DB_USER: postgres
   DB_PASSWORD: foobar
   DB_NAME: postgres
   DJANGO_SETTINGS_MODULE: project.settings.dockerdev
  env_file: .env
  #entrypoint: bash
  volumes:
  - ./:/app-v/
  # - ./pipenv:/home/test
  depends_on:
   postgres:
    condition: service_healthy
 postgres:
  image: mdillon/postgis:9.6-alpine
  volumes:
   - ./db:/var/lib/postgresql/data
  environment:
   POSTGRES_PASSWORD: foobar
   POSTGRES_USER: postgres
   PGDATA: /var/lib/postgresql/data
  healthcheck:
   test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
   interval: 15s
   timeout: 10s
   retries: 10
  ports:
   - '5432:5432'
