version: 2
jobs:
  build:
    working_directory: /home/aplikace
    docker:
      - image: python:3.9-bullseye

    steps:
      - checkout
      - run: echo "$(date +%Y).${CIRCLE_BUILD_NUM} $(git rev-parse --short HEAD)" > apps/cyklomapa/static/version.txt
      - setup_remote_docker:
          reusable: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="20.10.9"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
         name: Build Docker image
         command: docker build -t built-image .
      - run:
         name: Deploy test Docker image
         command: |
            if [ "$DOCKER_USER" != "" ] ; then
              TAG="$(date +%Y).${CIRCLE_BUILD_NUM}"
              docker tag built-image:latest auto0mat/cyklomapa:$TAG
              if [ "$CIRCLE_BRANCH" == "devel" ] ; then
                 docker tag built-image:latest auto0mat/cyklomapa-devel:latest
              fi
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push auto0mat/cyklomapa:$TAG
              if [ "$CIRCLE_BRANCH" == "devel" ] ; then
                 docker push auto0mat/cyklomapa-devel:latest
              fi
            fi
