# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0003_mesto_maxzoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upresneni',
            name='status',
            field=models.CharField(choices=[('novy', 'Nový'), ('reseno', 'V řešení'), ('vyreseno', 'Vyřešeno'), ('zamitnuto', 'Zamítnuto')], max_length=10),
        ),
    ]
