# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0004_auto_20160102_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('webmap.poi',),
        ),
        migrations.AlterField(
            model_name='upresneni',
            name='misto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cyklomapa.Poi'),
        ),
    ]
