# Generated by Django 2.2.19 on 2021-03-16 06:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0006_czechiaregions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CzechiaAccidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(null=True)),
                ('den', models.CharField(max_length=2, null=True)),
                ('cas', models.TimeField(null=True)),
                ('nasledky', models.CharField(max_length=20, null=True)),
                ('zavineni', models.CharField(max_length=50, null=True)),
                ('vozidlo', models.CharField(max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
