# Generated by Django 2.2.24 on 2021-06-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0007_czechiaaccidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='priciny_nehody',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
