# Generated by Django 2.2.24 on 2021-07-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0009_czechiaaccidents_lokalita'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='situovani',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
