# Generated by Django 2.2.24 on 2021-07-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0011_auto_20210708_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='identifikacni_cislo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
