# Generated by Django 2.2.24 on 2021-07-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0014_czechiaaccidents_druh_srazky_jedoucich_vozidel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czechiaaccidents',
            name='druh_srazky_jedoucich_vozidel',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
