# Generated by Django 2.2.24 on 2021-07-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0017_czechiaaccidents_druh_povrchu_vozovky'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='stav_povrchu_vozovky_v_dobe_nehody',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
