# Generated by Django 2.2.24 on 2021-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0018_czechiaaccidents_stav_povrchu_vozovky_v_dobe_nehody'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='stav_komunikace',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
