# Generated by Django 2.2.24 on 2021-07-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0019_czechiaaccidents_stav_komunikace'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='viditelnost',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
