# Generated by Django 2.2.24 on 2021-07-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0020_czechiaaccidents_viditelnost'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='deleni_komunikace',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
