# Generated by Django 2.2.24 on 2021-07-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0022_czechiaaccidents_rizeni_provozu_v_dobe_nehody'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='mistni_uprava_prednosti_v_jizde',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
