# Generated by Django 2.2.24 on 2021-07-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0023_czechiaaccidents_mistni_uprava_prednosti_v_jizde'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='specificka_mista_a_objekty_v_miste_nehody',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
