# Generated by Django 2.2.24 on 2021-07-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0025_czechiaaccidents_smerove_pomery'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='kategorie_chodce',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
