# Generated by Django 2.2.24 on 2021-07-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0029_czechiaaccidents_pocet_zucastnenych_vozidel'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='misto_dopravni_nehody',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
