# Generated by Django 2.2.24 on 2021-07-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0030_czechiaaccidents_misto_dopravni_nehody'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='druh_pozemni_komunikace',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
