# Generated by Django 2.2.24 on 2021-07-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0031_czechiaaccidents_druh_pozemni_komunikace'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='druh_krizujici_komunikace',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
