# Generated by Django 2.2.24 on 2021-07-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0032_czechiaaccidents_druh_krizujici_komunikace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='czechiaaccidents',
            old_name='vozidlo',
            new_name='druh_vozidla',
        ),
    ]
