# Generated by Django 2.2.24 on 2021-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0033_auto_20210722_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='charakteristika_vozidla',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
