# Generated by Django 2.2.24 on 2021-07-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0036_czechiaaccidents_vozidlo_po_nehode'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='smer_jizdy_nebo_postaveni_vozidla',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
