# Generated by Django 2.2.24 on 2021-07-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyklomapa', '0037_czechiaaccidents_smer_jizdy_nebo_postaveni_vozidla'),
    ]

    operations = [
        migrations.AddField(
            model_name='czechiaaccidents',
            name='stav_ridice',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
